name: Generate paths.json for notes

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  generate-paths-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

        # Step 2: Generate paths.json
        # The paths.json file is created in the repository root
      - name: Generate paths.json
        run: |
          # Find all files in src/notes directory and create paths.json
          find src/notes -type f | jq -R . | jq -s . > paths.json

      # Step 3: Commit and Push Changes
      - name: Commit and push changes
        run: |
          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Stage and commit paths.json
          git add paths.json
          
          # Commit only if there is a change in paths.json
          git diff --cached --exit-code || git commit -m "Update paths.json"
          
          # Push changes back to the repository
          git push