name: Generate paths.json for notes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-paths-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 5: Generate paths.json
      - name: Generate paths.json
        run: |
          rm -f paths.json
          find src/notes -type f | jq -R . | jq -s . > paths.json

      # Step 6: Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "carlosrrdev"
          git config user.email "rr.carlos.dev@gmail.com"
          git add paths.json
          git diff --cached --exit-code || git commit -m "Update paths.json"
          git push