name: Run Shell Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run the shell script
      - name: Run my script
        run: |
          chmod +x gen.sh
          bash gen.sh

      # Step 3: Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "carlosrrdev"
          git config user.email "rr.carlos.dev@gmail.com"
          git add /public/paths.json
          git diff --cached --exit-code || git commit -m "Update paths.json"
          git push