name: Run Shell Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run the shell script
      - name: Run my script
        run: |
          chmod +x gen.sh
          gen.sh